### ISSUE TITLE
Contributing md file

### ISSUE THREAD

**Issue by amitkumar-y** [aaryan2134/JPMC-Quant-Challenge-2022#2]
I think the project should have a contributing.md file, 
you can assign this to me I will add the file.

**Comment by aaryan2134** [comment]
Sure. You can go ahead and send a pull request once done
Thank you

**Comment by amitkumar-y** [comment]
Hi @aaryan2134 ,
I added the required file , have a look at it.
https://github.com/aaryan2134/JPMC-Quant-Challenge-2022/pull/3

**Comment by aaryan2134** [comment]
I have added a few comments. Please have a look

**Comment by aaryan2134** [comment]
Closing this issue now. You can continue to contribute to this project or https://github.com/aaryan2134/Engineering-Resources
